# Generated by Django 2.1.2 on 2018-10-30 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroniker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='subscribers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='subscribed_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
