# Generated by Django 2.1.2 on 2018-10-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroniker', '0002_auto_20181030_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='fixed_time',
            field=models.DateTimeField(blank=True, help_text='sets fixed time of day to run for daily jobs and longer', null=True, verbose_name='fixed time'),
        ),
    ]
